/**
 * Shared vocabulary for the deterministic path.
 *
 * The three fields in `SafetyFields` are the ones a wrong answer could cost
 * someone their health coverage. They are extracted here, by rules, and are
 * never generated by the model. Everything in this file exists to make that
 * boundary explicit in the type system rather than in a comment.
 */

export type StateCode = 'CA' | 'NY' | 'PA' | 'GA';

/**
 * Where the response deadline physically lives for a given state.
 *
 * This is the single most safety-critical piece of per-state knowledge in the
 * product. For three of the four states the deadline is NOT on the renewal form
 * at all, so a reader who photographs only the form is holding paperwork with no
 * visible deadline. Assuming the form carries the date is how a tool tells
 * someone they have no deadline when they have eleven days.
 */
export type DeadlineCarrier =
  /** Printed on the form itself. California fills it in on MC 216 page 1. */
  | 'form'
  /** On a separate cover notice mailed with the packet. New York, Georgia. */
  | 'notice'
  /** On the mailed packet or its envelope. Pennsylvania. */
  | 'packet';

/**
 * A field the engine could not read.
 *
 * The engine never reports "no deadline found", because a reader hears that as
 * "there is no deadline". It escalates instead, with the state's own phone
 * number attached.
 */
export const ESCALATE = 'ESCALATE' as const;
export type Escalate = typeof ESCALATE;

export interface Deadline {
  /** ISO date (YYYY-MM-DD), or ESCALATE when no date could be read. */
  value: string | Escalate;
  /** The literal text the date was read from, for showing provenance. */
  evidence?: string;
  /** Which phrasing pattern matched, for debugging and the eval table. */
  pattern?: string;
}

export interface CaseNumber {
  value: string | Escalate;
  evidence?: string;
  /** The label that anchored the match, e.g. "CASE NUMBER". */
  label?: string;
}

/** One of the 16 document categories a renewal can ask for. */
export interface RequiredDocument {
  id: DocumentId;
  /** Short, plain-language, one action per line. */
  label: string;
  /** The phrase in the packet that triggered this, for provenance. */
  evidence?: string;
}

export type DocumentId =
  | 'earned-income'
  | 'self-employment'
  | 'unearned-income'
  | 'loss-of-income'
  | 'prior-year-tax'
  | 'citizenship'
  | 'immigration'
  | 'residency'
  | 'household-changes'
  | 'resources'
  | 'property-vehicles'
  | 'life-insurance'
  | 'burial'
  | 'asset-transfers'
  | 'disability-medical'
  | 'work-hours';

export interface SafetyFields {
  state: StateCode | null;
  /** How confident state detection was, and what matched. */
  stateEvidence?: string;
  deadline: Deadline;
  caseNumber: CaseNumber;
  documents: RequiredDocument[];
}

export interface ExtractionResult extends SafetyFields {
  /** True when the packet appears to lack the document that carries the deadline. */
  missingDeadlineCarrier: boolean;
  /** Rendered guidance for the reader when something escalated. */
  escalation: string | null;
}
