/**
 * Demo prose, captured from this app's own engine.
 *
 * Nothing in DEMO_CACHE is authored. Every string was generated by Gemma 4 E2B
 * running on WebGPU in a real Chrome via `__renovaCaptureDemo()` in
 * src/demo/capture.ts, at the same fixed settings the live path uses
 * (temperature 0, fixed seed), against the same images in public/demo/. The
 * sampler is deterministic, so a live run on the same pages produces these
 * exact bytes; the eval suite and a paired live run keep this honest.
 *
 * At runtime the cache is never trusted: the cross-check, the glossary, and
 * the Spanish-intactness test all run again against the fields read live from
 * the document, exactly as they would for freshly generated prose.
 */
export interface CachedProse {
  explanationEn: string;
  explanationEs: string;
}

export interface DemoCache {
  capturedAt: string;
  model: string;
  settings: string;
  scenarios: Record<string, CachedProse>;
}

export const DEMO_CACHE: DemoCache = {
  capturedAt: '2026-07-30',
  model: 'litert-community/gemma-4-E2B-it-litert-lm',
  settings: 'temperature 0, fixed seed, 220 max output tokens',
  scenarios: {
    'ny-pair': {
      explanationEn:
        'This letter is about renewing your health coverage. You need to fill out a form. You must send some documents back to them. These documents include pay stubs and information about your savings.',
      explanationEs:
        'Esta carta es para renovar su cobertura de Medicaid. Usted debe completar un formulario de renovación. Debe enviar documentos como recibos de sueldo y cartas de beneficios. Recuerde enviar todos los documentos solicitados.',
    },
    'ca-mc216': {
      explanationEn:
        'This letter is about renewing your Medi-Cal coverage. You must send in a form by the due date. You need to send copies of certain documents. These documents include pay stubs, your last tax return, and benefit letters. You must also tell us about any changes in your life.',
      explanationEs:
        'Esta carta es sobre su renovación de Medi-Cal. Usted debe responder antes de la fecha límite. Envíe copias de sus recibos de pago y su declaración de impuestos. También debe informar sobre cualquier cambio en su hogar o ingresos.',
    },
    adversarial: {
      explanationEn:
        'This letter is about your health coverage. It is a notice of renewal. You must send back your renewal packet. The deadline for you to return your packet is August 27, 2026.',
      explanationEs:
        'Esta carta es una notificación de renovación de su cobertura de Medicaid. Usted debe enviar su paquete de renovación. La fecha límite para enviar su paquete es el veintisiete de agosto de dos mil veintiséis.',
    },
  },
};
